name: honkai_star_rail_database
description: "Database for Honkai Star Rail"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  path: any
  google_fonts: 6.1.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - assets/characters.json
    - assets/lightcones.json
    - assets/relics.json
    - lib/images/characters/
    - lib/images/lightcones/
    - lib/images/relics/
    - lib/images/skills/