name: honkai_star_rail_database
description: "Database for Honkai Star Rail"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  path: any
  google_fonts: 6.1.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/kafkascary.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/images/kafkascary.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/images/kafkascary.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/images/kafkascary.png"
flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - assets/characters.json
    - assets/lightcones.json
    - assets/relics.json
    - lib/images/edions/
    - lib/images/skills/
    - lib/images/characters/
    - lib/images/lightcones/
    - lib/images/relics/
    - lib/images/skills/